---
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: eureka-server
server:
  port: 8761
  address: localhost

eureka:
  instance:
    hostname: eureka-server
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  info:
    build:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,metrics
        exclude: health

info:
  application:
    parent:
      groupId: '@pom.parent.groupId@'
      artifactId: '@pom.parent.artifactId@'
      version: 0.0.1
    service:
      artifactId: '@pom.artifactId@'
      version: '@pom.version@'
      name: '@pom.name@'
      description: '@pom.description@'
  build:
    time: '@maven.build.timestamp@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
